space: default
instance-identity: dev

logging:
  level:
    com.fnjoin.k8s.controller.customresource.base: DEBUG
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){blue}%clr(:){red} %clr(%m){faint}%n'

spring:
  main:
    web-application-type: none
  output:
    ansi:
      enabled: ALWAYS
