apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.fnjoin.com
spec:
  scope: Namespaced
  group: fnjoin.com
  names:
    plural: mysqls
    singular: mysql
    kind: Mysql
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: storage
          type: string
          jsonPath: .spec.storage
          description: Storage capacity allocated
        - name: memory
          type: string
          jsonPath: .spec.memory
          description: Memory allocated
        - name: cpu
          type: string
          jsonPath: .spec.cpu
          description: CPU millis allocated
        - name: ready
          type: boolean
          jsonPath: .status.ready
          description: Is the database ready
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                ready:
                  type: boolean
                  default: false
            spec:
              type: object
              properties:
                cpu:
                  type: string
                memory:
                  type: string
                storage:
                  type: string