apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-controller
  namespace: mysql-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      type: native
  template:
    metadata:
      labels:
        type: native
    spec:
      restartPolicy: Always
      containers:
        - name: app
          image: fnjoin.com/mysql-controller-native:1.0
          env:
            - name: SPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCEIDENTITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
