apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-controller
rules:
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["watch", "get", "list", "create"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["watch", "get", "list", "create"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
  - apiGroups: ["fnjoin.com"]
    resources: ["mysqls"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-controller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mysql-controller
roleRef:
  kind: ClusterRole
  name: mysql-controller
  apiGroup: rbac.authorization.k8s.io
